Timing Precision 제외 전 섹션 번역 완료
geekhub-lab/geekhub-lab.github.io pull request #5
Opened 2018-07-06 16:27 UTC by mingrammer

### 07.07
모듈 속성 커스터마이징 번역 완료 (중간)

### 07.09
피드백 반영 및 전 섹션 번역 완료 (Bill 번역 섹션 제외)

2018-07-06 16:28 UTC, mingrammer commented
@Leop0ld 나머지 분량 번역중이고, 섹션 하나 끝나서 미리 리뷰 바람

2018-07-07 08:21 UTC, myungseokang commented
주말중으로 해놓을게요

2018-07-07 15:34 UTC, myungseokang requested changes

2018-07-07 15:34 UTC, Leop0ld commented on docs/blog/translation-python37-new-features/index.md
> +클래스에서 `thing.attr`을 호출하면 가장 먼저 `thing`에 `attr`이 정의되어 있는지 확인합니다. 정의되어 있지 않으면 특수 메서드인 `thing.__getattr__("attr")`이 호출됩니다. (이는 상당히 간략화한 것으로, 더 자세한 내용은 [이 글](http://blog.lerner.co.il/python-attributes/)을
정의할때 -> 정의할 때

2018-07-07 15:34 UTC, Leop0ld commented on docs/blog/translation-python37-new-features/index.md
> +클래스에서 `thing.attr`을 호출하면 가장 먼저 `thing`에 `attr`이 정의되어 있는지 확인합니다. 정의되어 있지 않으면 특수 메서드인 `thing.__getattr__("attr")`이 호출됩니다. (이는 상당히 간략화한 것으로, 더 자세한 내용은 [이 글](http://blog.lerner.co.il/python-attributes/)을
커스터마이징하는게 -> 커스터마이징하는 게

2018-07-07 15:34 UTC, Leop0ld commented on docs/blog/translation-python37-new-features/index.md
> +클래스에서 `thing.attr`을 호출하면 가장 먼저 `thing`에 `attr`이 정의되어 있는지 확인합니다. 정의되어 있지 않으면 특수 메서드인 `thing.__getattr__("attr")`이 호출됩니다. (이는 상당히 간략화한 것으로, 더 자세한 내용은 [이 글](http://blog.lerner.co.il/python-attributes/)을
그리고 Python 3.7 이전까지~~ 부분은 줄을 띄어야할 것 같아요. 본문에서는 띄워놨네욤

2018-07-07 15:34 UTC, Leop0ld commented on docs/blog/translation-python37-new-features/index.md
> +이 코드가 무슨일을 하는지 살펴보기 전에 `plugins` 디렉터리에 두 개의 파일을 더 추가해봅시다. 먼저 `plugins/plugin_1.py`를 다음과 같이 작성합니다.
무슨일을 -> 무슨 일을

2018-07-07 15:34 UTC, Leop0ld commented on docs/blog/translation-python37-new-features/index.md
> +뭐 딱히 혁신적인 기능인 것 같지는 않지만 무슨 일이 일어난건지 한 번 살펴봅시다. 기본적으로 `plugins.hello_1()` 호출이 가능하려면 `hello_1()`이 `plugins` 모듈에 정의되어 있거나 `plugins` 패키지의 `__init__.py`에 명시적으로 임포트 되어있어야 합니다. 이 예제에선 이 둘 모두 사용하지 않았습니다.
일어난건지 -> 일어난 건지

2018-07-07 15:34 UTC, Leop0ld commented on docs/blog/translation-python37-new-features/index.md
> +차이는 미묘한데, 패키지가 사용할 수 있는 함수를 직접 명시하는 대신, 각각의 함수가 자기 자신을 패키지의 일부로 등록하고 있습니다. 이렇게하면 사용할 수 있는 함수의 목록을 중앙 집중식으로 한 곳에서 관리하지 않고 나머지 코드와는 독립적으로 함수를 추가할 수 있는 간단한 구조를 만들 수 있습니다.
이렇게하면 -> 이렇게 하면

2018-07-07 15:34 UTC, Leop0ld commented on docs/blog/translation-python37-new-features/index.md
> +각 플러그인 함수가 `@register_plugin` 데코레이터로 감싸져 있음을 기억하세요. 이 데코레이터는 플러그인이 임포트되는 시점에 호출되며 실제로 `PLUGINS` 딕셔너리에 플러그인을 채우는데 사용됩니다. 플러그인 파일중 하나를 직접 임포트 해보면 채워지는 과정을 볼 수 있습니다.
채우는데 -> 채우는 데

2018-07-07 15:34 UTC, Leop0ld commented on docs/blog/translation-python37-new-features/index.md
> +각 플러그인 함수가 `@register_plugin` 데코레이터로 감싸져 있음을 기억하세요. 이 데코레이터는 플러그인이 임포트되는 시점에 호출되며 실제로 `PLUGINS` 딕셔너리에 플러그인을 채우는데 사용됩니다. 플러그인 파일중 하나를 직접 임포트 해보면 채워지는 과정을 볼 수 있습니다.
플러그인 파일중 -> 플러그인 파일 중

2018-07-07 15:34 UTC, Leop0ld commented on docs/blog/translation-python37-new-features/index.md
> +위 정보도 물론 유용하겠지만, 우리는 사용할 수 있는 플러그인들을 보여주는데 더 관심있습니다. Python 3.7에서는 `__dir__()` 특수 함수를 사용해 모듈의 `dir()` 반환값을 커스터마이징 할 수 있습니다. `plugins/__init__.py`에서 이 함수는 모든 플러그인을 임포트한 뒤 플러그인들의 이름을 나열합니다.
보여주는데 -> 보여주는 데에

2018-07-08 16:44 UTC, mingrammer commented
@Leop0ld 피드백 반영 및 전 섹션 번역 완료 (Bill 번역 섹션 제외 )

2018-07-09 00:23 UTC, myungseokang requested changes

2018-07-09 00:23 UTC, myungseokang commented on docs/blog/translation-python37-new-features/index.md
> +Python 3.6의 CPython 구현체에는 순서를 가진 딕셔너리가 구현되어 있습니다. ([PyPy](http://pypy.org/)에도 있습니다) 즉, 딕셔너리의 항목들은 삽입된 순서대로 순회됩니다. 첫번째 예제에서는 Python 3.5를, 두번째 예제에서는 Python 3.6을 사용했습니다.
첫번쨰 -> 첫 번쨰

2018-07-09 00:23 UTC, myungseokang commented on docs/blog/translation-python37-new-features/index.md
> +Python 3.6의 CPython 구현체에는 순서를 가진 딕셔너리가 구현되어 있습니다. ([PyPy](http://pypy.org/)에도 있습니다) 즉, 딕셔너리의 항목들은 삽입된 순서대로 순회됩니다. 첫번째 예제에서는 Python 3.5를, 두번째 예제에서는 Python 3.6을 사용했습니다.
마찬가지로 두번째 -> 두 번째

2018-07-09 00:23 UTC, myungseokang commented on docs/blog/translation-python37-new-features/index.md
> +Python 3.6에서 이 순서는 단지 `dict` 구현체의 (훌륭한) 결과일뿐입니다. 그러나 Python 3.7에서는 삽입 순서를 유지하는 딕셔너리가 [언어 명세](https://mail.python.org/pipermail/python-dev/2017-December/151283.html)의 일부로 들어갔습니다. 따라서 이 기능은 Python 3.7
결과일뿐입니다 -> 결과일 뿐입니다

2018-07-09 00:23 UTC, myungseokang commented on docs/blog/translation-python37-new-features/index.md
> +Python 3.5에서는 [async 및 await 문법을 활용한 코루틴](https://www.python.org/dev/peps/pep-0492/)이 소개되었습니다. 이전 버전과의 호환성 문제를 피하기위해 `async`와 `await`는 예약된 키워드 목록에 추가되지 않았습니다. 즉, `async` 및 `await`라는 이름을 가진 변수나 함수를 정의
피하기위해 -> 피하기 위해

2018-07-09 00:23 UTC, myungseokang commented on docs/blog/translation-python37-new-features/index.md
> +Python 프로젝트를 패키징 할 때 마주하는 문제중 하나는 프로젝트에 필요한 데이터 파일과 같은 프로젝트 리소스를 어떻게 처리할지 결정하는 일입니다. 다음은 흔히 사용되는 몇 가지 옵션들입니다.
문제중 -> 문제 중

2018-07-09 00:23 UTC, myungseokang commented on docs/blog/translation-python37-new-features/index.md
> +이들 각각에는 단점이 있습니다. 첫번째 옵션은 이식성이 떨어지며, `__file__`은 이식성은 뛰어나지만 설치된 Python 프로젝트가 zip으로 끝나 `__file__` 속성이 없을 수도 있습니다. 그리고 세번째 옵션은 상당히 느립니다.
첫번째 -> 첫 번째
두번째 -> 두 번째
세번째 -> 세 번째

번째 << 이 부분이 의존 명사라서 띄어쓰는 게 맞답니다

2018-07-09 00:23 UTC, myungseokang commented on docs/blog/translation-python37-new-features/index.md
> +`cumulative` 열은 임포트할 때 소요된 누적 시간을 마이크로초로 보여줍니다. 이 예제에서는 `plugins` 임포트시 약 0.03초가 소요되었으며 `importlib.resources`를 임포트하는데 가장 많은 시간이 소요되었습니다. `self` 열은 중첩을 제외한 단일 임포트 시간을 보여줍니다.
임포트하는데 -> 임포트하는 데

2018-07-09 00:23 UTC, myungseokang commented on docs/blog/translation-python37-new-features/index.md
> +자 이제 그럼 조금 더 복잡한 질문들을 해보겠습니다. 여러분의 프로덕션 환경을 Python 3.7로 업그레이드 해야합니까? 개인 프로젝트에서 Python 3.7의 새로운 기능을 사용해야하나요?
사용해야하나요? -> 사용해야 하나요?

2018-07-09 00:23 UTC, myungseokang commented on docs/blog/translation-python37-new-features/index.md
> +분명히 주의해야할건 프로덕션 환경을 업그레이드 하기 전에는 항상 철저한 테스트를 거쳐야 한다는 것입니다. Python 3.7에 도입된 일부기능들이 기존 코드를 망가뜨릴수도 있습니다 (`async`와 `await`가 키워드로 추가되었다는점이 한 예입니다). 이미 최신 버전의 Python을 사용하고 있다면 3.7로의 업그레이드는 매우 수월할 것입니다. 조금
주의해야할건 -> 주의해야할 건

2018-07-09 00:23 UTC, myungseokang commented on docs/blog/translation-python37-new-features/index.md
> +분명히 주의해야할건 프로덕션 환경을 업그레이드 하기 전에는 항상 철저한 테스트를 거쳐야 한다는 것입니다. Python 3.7에 도입된 일부기능들이 기존 코드를 망가뜨릴수도 있습니다 (`async`와 `await`가 키워드로 추가되었다는점이 한 예입니다). 이미 최신 버전의 Python을 사용하고 있다면 3.7로의 업그레이드는 매우 수월할 것입니다. 조금
일부기능들이 -> 일부 기능들이

2018-07-09 00:23 UTC, myungseokang commented on docs/blog/translation-python37-new-features/index.md
> +여러분의 프로젝트가 3.7에서만 동작해야한다고 주장하기는 조금 어렵습니다. Python 3.7의 새로운 기능중 상당수는 Python 3.6에서 백포트로 사용할 수 있거나 (데이터 클래스, `importlib.resources`) 그저 단순한 편의 기능중 하나 (빠른 로드 및 메서드 호출 속도, 편리한 디버깅 및 `-X` 옵션)이기 때문입니다. 후자의 경우
동작해야한다고 -> 동작해야 한다고

2018-07-09 00:23 UTC, myungseokang commented on docs/blog/translation-python37-new-features/index.md
> +여러분의 프로젝트가 3.7에서만 동작해야한다고 주장하기는 조금 어렵습니다. Python 3.7의 새로운 기능중 상당수는 Python 3.6에서 백포트로 사용할 수 있거나 (데이터 클래스, `importlib.resources`) 그저 단순한 편의 기능중 하나 (빠른 로드 및 메서드 호출 속도, 편리한 디버깅 및 `-X` 옵션)이기 때문입니다. 후자의 경우
편의 기능중 하나 -> 편의 기능 중 하나

2018-07-09 00:23 UTC, myungseokang commented on docs/blog/translation-python37-new-features/index.md
> +코드가 Python 3.7에만 의존하도록 만드는 큰 기능들로는 [모듈에서의 \_\_getattr\_\_()](#모듈-속성-커스터마이징), [타입 힌팅에서의 전방 참조](#향상된-타이핑) 및 [나노초 시간 함수](#시간-정밀도)가 있습니다. 만약 이 기능들중 어느 것이라도 정말로 필요하다면, 여러분은 계속해서 여러분의 요구사항을 충족시켜나가야 합니다. 그렇
하는게 -> 하는 게

2018-07-09 03:37 UTC, mingrammer commented
@Leop0ld 완료오

2018-07-09 04:00 UTC, myungseokang approved these changes
LGTM 👍  수고하셨어요!

2018-07-09 04:07 UTC, merged