add timing precision
geekhub-lab/geekhub-lab.github.io pull request #6
Opened 2018-07-07 05:36 UTC by Bill-Park

Leave review please.

2018-07-07 06:40 UTC, mingrammer requested changes

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +파이썬 3.7에서는 [PEP 564](https://www.python.org/dev/peps/pep-0564/)에 설명된 [time](https://docs.python.org/3/library/time.html) 모듈의 새로운 함수가 있습니다.
1. 파이썬 => Python 통일
2. Python 3.7에서는 time 모듈에 PEP 564에서 소개된 몇 가지 새로운 기능이 추가되었습니다.

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +주목할만한 6개의 함수를 소개합니다.
다음의 주목할만한 6개의 함수가 추가되었습니다?

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +- clock_gettime_ns() : 명시된 클럭의 시간값을 리턴합니다.
리턴 => 반환

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +- clock_gettime_ns() : 명시된 클럭의 시간값을 리턴합니다.
Bold 하이라이팅 모두 추가 바람

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +- process_time_ns() : 시스템과 현재 프로세스(sleep 시간은 포함하지 않습니다.)에 대한 CPU시간의 합을 리턴합니다.
현재 프로세스의 시스템 및 유저 CPU 시간의 합을 나노초 단위로 반환합니다?

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +- perf_counter_ns() : 퍼포먼스 카운터의 값을 반환합니다. 클럭은 특별히 짧은 시간을 측정하기 위해 고안되었습니다.
짧은 간격을 측정하기 위해 특별히 고안된 클럭인 퍼포먼스 카운터의 값을 나노초 단위로 반환합니다.

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +- clock_gettime_ns() : 명시된 클럭의 시간값을 리턴합니다.
명시된 => 지정된

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +- monotinic_ns() : 변하지 않는(ex:서머타임)상대적인 클럭의 시간값을 리턴합니다.
거꾸로 돌릴 수 없는 (가령, 서머타임 때문에 시간이 앞당겨지는 경우가 있음) 단조 증가 클럭의 시간을 나노초 단위로 반환합니다. (단조 증가 클럭이란, 시간이 튀지 않고 시간값이 단조롭게 증가만 하는 클럭을 말함)

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +어떤 의미에서는 새로운 기능이 추가된 것이 없다고 할 수 있습니다.
번역체 => 어떤 의미에서는 딱히 새로울게 없습니다.?

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +각 함수는 `_ns`가 없는 기존의 함수와 비슷합니다.
각 함수는 `_ns` 접미사가 없는 기존에 이미 존재하는 함수들과 유사합니다.?

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +차이점으로 기존 함수는 `float`형의 초 단위를 리턴하지만, 새 함수는 `int`형의 나노초 단위를 리턴합니다.
차이점이라고하면 기존 함수는 초를 `float`형으로 반환하지만, 새로 추가된 함수는 나노초를 `int`형으로 반환한다는 것입니다?

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +대부분의 어플리케이션에서는 시간 측정과 관련해서 주목하지 않을수도 있습니다.
대부분의 애플리케이션에서는 새로운 나노초 함수와 기존의 나노초 함수의 차이가 크게 와닿지 않을수도 있습니다?

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +그러나 새 함수는 `float`형 대신 `int`형을 사용하기에 더 쉽다고 할 수 있습니다.
그러나 새 함수는 `float` 대신 `int`를 사용하기 때문에 다루기가 좀 더 수월합니다.?

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +부동소수점(Floating point)숫자들은 [태생적 부정확함](https://docs.python.org/3/tutorial/floatingpoint.html)이 있습니다.
부동소수점(Float point) 숫자 : 띄어쓰기

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +부동소수점(Floating point)숫자들은 [태생적 부정확함](https://docs.python.org/3/tutorial/floatingpoint.html)이 있습니다.
~ 숫자들은 [태생적으로 부정확](https://docs.python.org/3/tutorial/floatingpoint.html)합니다.

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +이것은 파이썬의 문제가 아닌 컴퓨터가 유한한 비트를 사용해 무한한 소수를 표현하는 결과입니다.
이는 Python의 문제가 아니라 컴퓨터가 유한한 비트 수를 사용해 무한 소수를 표현해야하는 한계로 인해 나타난 결과입니다.?

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +파이썬의 `float`형은 [IEEE 754 표준](https://en.wikipedia.org/wiki/IEEE_754)을 따르고 53개의 유효비트를 사용합니다.
Python

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +104일보다 많은 시간(2의 53승 혹은 [9000조 나노초](https://en.wikipedia.org/wiki/Names_of_large_numbers)은 나노초 정밀도로 `float`형으로 표현할 수 없습니다.
~~은 `float`으로는 나노초의 정밀도를 표현할 수 없습니다?

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +예시와 같이 `time.time()`은 1970년 1월 1일부터 흐른 시간을 초 단위로 리턴합니다.
반환

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +나노초로 반환되는 `int`형 숫자는 나노초 정밀도의 한계에 구애받지 않습니다.
위 문장이랑 하나로 이어서, ~~ 무한하기 때문에 ~~ `int`형 나노초는 시간값과 무관하게 항상 나노초 정밀도를 가집니다.?

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +이 함수는 `_ns`버전에서 엄청난 개선을 이뤘습니다.
`_ns` 버전 : 띄어쓰기

엄청난 개선을 이뤄냈습니다?

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +`time.time_ns()`의 해상도는 `time.time()`보다 [약 3배의 성능](https://www.python.org/dev/peps/pep-0564/#analysis)을 보여줍니다.
~의 정밀도는 ~보다 약 3배 이상 향상되었습니다.

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +그런데 나노초가 뭔가요?
::: tip
그런데 나노초가 뭔가요? 나노초란, 기술적으로는 10억 분의 1 혹은 1e-9 초를 말합니다. 와닿는 숫자는 아닙니다. 좀 더 자세한 설명은 [Grace Hopper](https://en.wikipedia.org/wiki/Grace_Hopper#Anecdotes)의 [나노초 설명 영상](https://www.youtube.com/watch?v=JEpsKnWZrJ8)을 참고하세요.
:::

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +덧붙여서, 만약 나노초 정밀도의 시간을 이용해야 한다면 `datetime` 표준 라이브러리는 입력받지 못합니다.
여담이지만, 만약 나노초 정밀도의 시간을 다루는 경우 `datetime` 표준 라이브러리는 사용하기 어려울 수도 있습니다.?

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +[`astropy.time`](http://docs.astropy.org/en/stable/time/)패키지는 우주의 나이 이상의 시간을 나노초 단위 이하의 정밀도로 보장하기 때문입니다.
)패키지 => ) 패키지

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +[`astropy.time`](http://docs.astropy.org/en/stable/time/)패키지는 우주의 나이 이상의 시간을 나노초 단위 이하의 정밀도로 보장하기 때문입니다.
astropy.time 패키지는 우주의 나이 이상의 시간을 나노초 이하의 정밀도로 보장하는 두 float형 객체를 사용하는 datetime을 지원합니다.?

2018-07-07 06:40 UTC, mingrammer commented on docs/blog/translation-python37-new-features/index.md
> +`astropy`의 마지막 버전은 파이썬 3.5 이후 버전에서 사용 가능합니다.
`astropy`의 최신 버전은 Python 3.5 이후 버전에서 사용할 수 있습니다.

2018-07-10 02:58 UTC, mingrammer commented
오늘까지 힘들면 걍 내가 하겠음

2018-07-10 05:01 UTC, Bill-Park commented
문법, 단어수정 완료

2018-07-10 05:25 UTC, merged